### ISSUE TITLE
8.0.1-rc_alignment pkls naming includes extension

### ISSUE THREAD

**Issue by matsojr22** [asoronow/belljar#11]
alignment pkls are naming as below:
`Annotation_M470_s020.png.pkl`
rather than the expected:
`Annotation_M470_s020.pkl`

bug? feature? you decide! I have not run the 'int to pkl' script using the oddball names, I've been manually correcting them to avoid any issues and wasted time. intensity to pkl works fine if I change to match the intensity files example.pkl & example.ome

**Comment by asoronow** [comment]
Fixed in 8.0.2-rc
