### ISSUE TITLE
belljar 4.0.0 can't find class_map.pkl on align step after closing napari

### ISSUE THREAD

**Issue by matsojr22** [asoronow/belljar#2]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File ~\OneDrive\Desktop\belljar_4.0.0\belljar-win32-x64\resources\app\py\mapToAtlas.py:379, in finishAlignment()
    374     section = atlas[
    375         int(predictions[imageName]), :, : x_val
    376     ]   
    378 tissue = images[i]
--> 379 warped_labels, warped_atlas, color_label = register_to_atlas(
        tissue = <class 'numpy.ndarray'> (633, 806) uint8
        label = <class 'numpy.ndarray'> (800, 1140) uint32
        section = <class 'numpy.ndarray'> (800, 1140) float32
    380     tissue, section, label, "./csv/class_map.pkl"
    381 )
    382 cv2.imwrite(
    383     str(outputPath / f"Atlas_{imageName.split('.')[0]}.png"), warped_atlas
    384 )
    385 # write label

File ~\OneDrive\Desktop\belljar_4.0.0\belljar-win32-x64\resources\app\py\demons.py:11, in register_to_atlas(tissue=<class 'numpy.ndarray'> (633, 806) uint8, section=<class 'numpy.ndarray'> (800, 1140) float32, label=<class 'numpy.ndarray'> (800, 1140) uint32, class_map_path='./csv/class_map.pkl')
      9 def register_to_atlas(tissue, section, label, class_map_path):
     10     """Uses demons registration to register a tissue section to the atlas"""
---> 11     with open(class_map_path, "rb") as f:
        class_map_path = './csv/class_map.pkl'
     12         classMap = pickle.load(f)
     13         classMap[997] = {"index": 1326, "name": "undefined", "color": [0, 0, 0]}

FileNotFoundError: [Errno 2] No such file or directory: './csv/class_map.pkl'

**Comment by asoronow** [comment]
I have located the issue. It seems that I need to put in another direct ref for this file since the context is all messed up when called from PyShell.

**Comment by asoronow** [comment]
This has been fixed in the latest release.
