### ISSUE TITLE
Cannot access link to sample dataset

### ISSUE THREAD

**Issue by beniroquai** [asoronow/belljar#26]
First of all: this looks like a great project. Although I'm not really from the field of neuroscience I'm really impressed how professionally made the distribution of the software has been done. Great work! 
I was looking for a way to ship our python based microscopy software [ImSwitch](https://github.com/openUC2/imswitch). And to my surprise you are ven using Napari as the main viewer, too. 

I wanted to fully test Belljar and therefore download the sample dataset, but the link in the PDF seems to be non-interactive. Would you mind sharing the link again? Thanks a lot!

**Comment by beniroquai** [comment]
Never mind, I guess I found it here: https://storage.googleapis.com/belljar_updates/belljar-sample.zip

**Comment by asoronow** [comment]
Hey, thanks. I'm glad you like the project! The current guide is a bit out of date, so it may have some issues, thanks for reposting the link. I'm putting out a newer version soon, let me know if you have any other questions.

**Comment by asoronow** [comment]
> First of all: this looks like a great project. Although I'm not really from the field of neuroscience I'm really impressed how professionally made the distribution of the software has been done. Great work! I was looking for a way to ship our python based microscopy software [ImSwitch](https://github.com/openUC2/imswitch). And to my surprise you are ven using Napari as the main viewer, too.
> 
> I wanted to fully test Belljar and therefore download the sample dataset, but the link in the PDF seems to be non-interactive. Would you mind sharing the link again? Thanks a lot!

I have updated the instructions in the latest commit so you can get a feel for the new version.

**Comment by beniroquai** [comment]
That's great! Thanks a lot! And again thanks a lot for your work. This is the first step to make python software much more reproducible in its widespread adoption. I'm hassling with some problems on the windows side, but anyway. Great job! :-)
