### ISSUE TITLE
Failed to align M239_s003 Likely due to masking error

### ISSUE THREAD

**Issue by HyGuy7** [asoronow/belljar#34]
RuntimeError                              Traceback (most recent call last)
~\Downloads\belljar-win32-x64-9.5.2\belljar-win32-x64\resources\app\py\map.py in ?(self=<__main__.AlignmentController object>)
    871                 )
    872                 current_slice.image = masked_atlas
    873                 current_slice.label = masked_annotation
    874 
--> 875             warped_labels, warped_atlas, color_label = current_slice.get_registered(
    876                 sample,
    877             )
    878 

~\Downloads\belljar-win32-x64-9.5.2\belljar-win32-x64\resources\app\py\map.py in ?(self=<__main__.AtlasSlice object>, tissue=<class 'numpy.ndarray'> (633, 905) uint8)
    254             except:
    255                 self.mask = None
    256                 print("Bad mask! Reset next alignment.")
    257 
--> 258         warped_labels, warped_atlas, color_label = register_to_atlas(
    259             tissue,
    260             self.image,
    261             self.label,

~\Downloads\belljar-win32-x64-9.5.2\belljar-win32-x64\resources\app\py\demons.py in ?(tissue=<class 'numpy.ndarray'> (633, 905) uint8, section=<class 'numpy.ndarray'> (800, 1140) uint8, label=<SimpleITK.SimpleITK.Image; proxy of <Swig Objec...e 'itk::simple::Image *' at 0x00000271D4E676F0> >, structure_map_path=r'C:\Users\Hylen\Downloads\belljar-win32-x64-9.5.2...jar-win32-x64\resources\app\csv\structure_map.pkl')
    215     label = sitk.GetImageFromArray(label, isVector=False)
    216 
    217     # resize fixed to match moving
    218     moving = match_histograms(fixed, moving)
--> 219     tx = multimodal_registration(fixed, moving)
    220 
    221     resampler = sitk.ResampleImageFilter()
    222     resampler.SetReferenceImage(fixed)

~\Downloads\belljar-win32-x64-9.5.2\belljar-win32-x64\resources\app\py\demons.py in ?(fixed=<SimpleITK.SimpleITK.Image; proxy of <Swig Objec...e 'itk::simple::Image *' at 0x00000271D26FBED0> >, moving=<SimpleITK.SimpleITK.Image; proxy of <Swig Objec...e 'itk::simple::Image *' at 0x00000271D4E67330> >)
     85     R.SetSmoothingSigmasPerLevel(smoothingSigmas=[3, 2, 0])
     86     R.SetInitialTransform(initialTx)
     87     R.SetInterpolator(sitk.sitkLinear)
     88 
---> 89     outTx1 = R.Execute(fixed, moving)
     90 
     91     # Resample the moving image using the initial transformation
     92     resampled_moving = sitk.Resample(

~\.belljar\benv\lib\site-packages\SimpleITK\SimpleITK.py in ?(self=<SimpleITK.SimpleITK.ImageRegistrationMethod; pr...ageRegistrationMethod *' at 0x00000271F1B27F00> >, fixed=<SimpleITK.SimpleITK.Image; proxy of <Swig Objec...e 'itk::simple::Image *' at 0x00000271D26FBED0> >, moving=<SimpleITK.SimpleITK.Image; proxy of <Swig Objec...e 'itk::simple::Image *' at 0x00000271D4E67330> >)
  10848         Optimize the configured registration problem.
  10849 
  10850 
  10851         """
> 10852         val = _SimpleITK.ImageRegistrationMethod_Execute(self, fixed, moving)
  10853 
  10854         val = val.Downcast()
  10855 

RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: D:\a\1\sitk-build\ITK-prefix\include\ITK-5.3\itkImageBase.hxx:79:
ITK ERROR: Image(000002744DD05520): Zero-valued spacing is not supported and may result in undefined behavior.
Refusing to change spacing from [1, 1] to [5.46543, 0]

**Comment by asoronow** [comment]
Fixed in 10.1.0
